config/routes.rb
Rails.application.routes.draw do
  resources :stations
  resources :properties
  root 'properties#index'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :stations
    validates :property, :rent, :adress,
        :building_age, presence: true
    validates :rent, numericality: true   
    accepts_nested_attributes_for :stations, :allow_destroy => true
        def check
            if how_many_minutes_walks.present? && how_many_minutes_walks1.present?
                if how_many_minutes_walks <= how_many_minutes_walks1
                    errors.add(:how_many_minutes_walks, 'Very well')
                end
            end
        end
end

app/models/station.rb
class Station < ApplicationRecord
    belongs_to :property, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  def index
    @properties = Property.all
  end

  # GET /properties/1
  def show
    @station = Station.all
  end

  # GET /properties/new
  def new
    @property = Property.new
    2.times { @property.stations.build }
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  def create
    @property = Property.new(property_params)
   
    if @property.save
      redirect_to @property, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /properties/1
  def update
    if @property.update(property_params)
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /properties/1
  def destroy
    @property.destroy
    redirect_to properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def property_params
     params.require(:property).permit(:property, :rent, :adress, :building_age, :remarks, stations_attributes: [:id, :name_of_railway_line, :statation_name, :how_many_minutes_walks])
      # params.require(:property).permit(:property, :rent, :adress, :building_age, :remarks, stations_attributes:  Station.attributes_names.map(&:to_sym).push(:_destroy))

    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  def index
    @stations = Station.all
  end

  # GET /stations/1
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  def create
    @station = Station.new(station_params)

    if @station.save
      redirect_to @station, notice: 'Station was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stations/1
  def update
    if @station.update(station_params)
      redirect_to @station, notice: 'Station was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stations/1
  def destroy
    @station.destroy
    redirect_to stations_url, notice: 'Station was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def station_params
      params.require(:station).permit(:name_of_railway_line, :statation_name, :how_many_minutes_walks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="prop">
  <div class="field">
    <%= f.label :property %>
    <%= f.text_field :property %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.text_field :rent %>
  </div>

  <div class="field">
    <%= f.label :adress %>
    <%= f.text_field :adress %>
  </div>

  <div class="field">
    <%= f.label :building_age %>
    <%= f.number_field :building_age %>
  </div>

  <div class="field">
    <%= f.label :remarks %>
    <%= f.text_area :remarks %>
  </div>
  </div >
 <hr>
   
 
  <%= f.fields_for :stations do |s| %>
   
    <h2><b>Name of railway line </b></h2>
    <div class="field">
    <%= s.label :name_of_railway_line %>
    <%= s.text_field :name_of_railway_line %>
  </div>

  <div class="field">
    <%= s.label :statation_name %>
    <%= s.text_field :statation_name %>
  </div>

  <div class="field">
    <%= s.label :how_many_minutes_walks %>
    <%= s.number_field :how_many_minutes_walks %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Rent</th>
      <th>Adress</th>
      <th>Building age</th>
      <th>Remarks</th>
             
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property %></td>
        <td><%= property.rent %></td>
        <td><%= property.adress %></td>
        <td><%= property.building_age %></td>
        <td><%= property.remarks %></td>
         
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>
<div class="prop">
<h1><b>Property Details</b></h1>
<p>
  <strong>Property:</strong>
  <%= @property.property %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @property.adress %>
</p>

<p>
  <strong>Building age:</strong>
  <%= @property.building_age %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @property.remarks %>
</p>
</div>
</hr>
 
<% @property.stations.each do |poor| %>
  <% if @property.id == poor.property_id %>
    <h2><b>Nearest station </b></h2>
    <p>
      <strong>Name of railway line:</strong>
      <%= poor.name_of_railway_line %>
    </p>

    <p>
      <strong>Statation name:</strong>
      <%= poor.statation_name %>
    </p>

    <p>
      <strong>How many minutes walks:</strong>
      <%= poor.how_many_minutes_walks %>
    </p>
  <% end %>
<% end %>
<div class="links">
  <%= link_to 'Edit', edit_property_path(@property) %> |
  <%= link_to 'Back', properties_path %>
</div>

app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_of_railway_line %>
    <%= f.text_field :name_of_railway_line %>
  </div>

  <div class="field">
    <%= f.label :statation_name %>
    <%= f.text_field :statation_name %>
  </div>

  <div class="field">
    <%= f.label :how_many_minutes_walks %>
    <%= f.number_field :how_many_minutes_walks %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name of railway line</th>
      <th>Statation name</th>
      <th>How many minutes walks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name_of_railway_line %></td>
        <td><%= station.statation_name %></td>
        <td><%= station.how_many_minutes_walks %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name of railway line:</strong>
  <%= @station.name_of_railway_line %>
</p>

<p>
  <strong>Statation name:</strong>
  <%= @station.statation_name %>
</p>

<p>
  <strong>How many minutes walks:</strong>
  <%= @station.how_many_minutes_walks %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>